import { describe, it, expect } from 'vitest'
import { exportGcode } from '@/util/slicer/algorithms/gcodeExport'
import type { SlicerConfig, LayerToolpath } from '@/util/slicer/types'

function createTestConfig(overrides: Partial<SlicerConfig> = {}): SlicerConfig {
    return {
        layerHeight: 0.2,
        firstLayerHeight: 0.3,
        wallCount: 3,
        wallSpeed: 40,
        topLayers: 4,
        bottomLayers: 4,
        infillDensity: 0.2,
        infillPattern: 'grid',
        infillSpeed: 60,
        printSpeed: 60,
        travelSpeed: 150,
        firstLayerSpeed: 20,
        nozzleTemp: 210,
        bedTemp: 60,
        firstLayerNozzleTemp: 215,
        firstLayerBedTemp: 65,
        retractDistance: 1.0,
        retractSpeed: 40,
        retractLift: 0.2,
        nozzleDiameter: 0.4,
        filamentDiameter: 1.75,
        extrusionMultiplier: 1.0,
        lineWidth: 0.44,
        buildVolumeX: 220,
        buildVolumeY: 220,
        buildVolumeZ: 250,
        enableSupport: false,
        supportDensity: 0.15,
        supportAngle: 50,
        skirtLoops: 2,
        skirtDistance: 5,
        brimWidth: 0,
        adhesionType: 'none',
        adhesionBrimWidth: 5,
        adhesionBrimLines: 5,
        mouseEarDiameter: 10,
        mouseEarLayers: 1,
        mouseEarPositions: [],
        raftPadPositions: [],
        raftPadLayers: 3,
        raftPadGap: 0.15,
        fanSpeed: 255,
        fanStartLayer: 2,
        ...overrides,
    }
}

describe('gcodeExport start prime safety', () => {
    it('keeps prime-line cross-section under Klipper max_extrude_cross_section default guard', () => {
        const config = createTestConfig()
        const gcode = exportGcode([] as LayerToolpath[], config)

        const primeMatch = gcode.match(/G1 X60\.000 Y5\.000 E([0-9]+\.[0-9]+)/)
        expect(primeMatch).not.toBeNull()

        const ePrime = Number(primeMatch![1])
        const primeDistanceMm = 55
        const filamentArea = Math.PI * (config.filamentDiameter / 2) ** 2
        const crossSection = (ePrime * filamentArea) / primeDistanceMm

        expect(crossSection).toBeLessThan(0.64)
    })
})

describe('gcodeExport custom start/end gcode', () => {
    it('uses custom start gcode with variable substitution when provided', () => {
        const config = createTestConfig({
            customStartGcode: 'PRINT_START ETMP={nozzle_temp} BTMP={bed_temp} LAYER_HEIGHT={layer_height}',
            nozzleTemp: 250,
            bedTemp: 80,
            layerHeight: 0.3,
        })
        const gcode = exportGcode([] as LayerToolpath[], config)

        expect(gcode).toContain('PRINT_START ETMP=250 BTMP=80 LAYER_HEIGHT=0.3')
        // Should NOT contain the default G28 home command
        expect(gcode).not.toContain('G28 ; Home all axes')
    })

    it('uses default start gcode when customStartGcode is empty', () => {
        const config = createTestConfig({ customStartGcode: '' })
        const gcode = exportGcode([] as LayerToolpath[], config)

        expect(gcode).toContain('G28 ; Home all axes')
    })

    it('uses default start gcode when customStartGcode is undefined', () => {
        const config = createTestConfig()
        const gcode = exportGcode([] as LayerToolpath[], config)

        expect(gcode).toContain('G28 ; Home all axes')
    })

    it('uses custom end gcode with variable substitution when provided', () => {
        const config = createTestConfig({
            customEndGcode: 'PRINT_END',
        })
        const gcode = exportGcode([] as LayerToolpath[], config)

        expect(gcode).toContain('PRINT_END')
        expect(gcode).not.toContain('G1 X5 Y200 F6000 ; Present print')
    })

    it('uses default end gcode when customEndGcode is not set', () => {
        const config = createTestConfig()
        const gcode = exportGcode([] as LayerToolpath[], config)

        expect(gcode).toContain('M104 S0 ; Turn off nozzle')
    })

    it('preserves header comments with custom start gcode', () => {
        const config = createTestConfig({
            customStartGcode: 'PRINT_START',
            layerHeight: 0.2,
        })
        const gcode = exportGcode([] as LayerToolpath[], config)

        expect(gcode).toContain('; Generated by Mainsail Slicer')
        expect(gcode).toContain('; Layer height: 0.2mm')
    })

    it('substitutes first_layer variables in custom start gcode', () => {
        const config = createTestConfig({
            customStartGcode: 'M104 S{first_layer_nozzle_temp}\nM140 S{first_layer_bed_temp}',
            firstLayerNozzleTemp: 220,
            firstLayerBedTemp: 70,
        })
        const gcode = exportGcode([] as LayerToolpath[], config)

        expect(gcode).toContain('M104 S220')
        expect(gcode).toContain('M140 S70')
    })

    it('leaves unknown variables untouched', () => {
        const config = createTestConfig({
            customStartGcode: 'PRINT_START CUSTOM={unknown_var}',
        })
        const gcode = exportGcode([] as LayerToolpath[], config)

        expect(gcode).toContain('{unknown_var}')
    })
})

function createTestLayer(index: number, z: number): LayerToolpath {
    return {
        z,
        layerIndex: index,
        segments: [{
            from: { x: 10, y: 10 },
            to: { x: 20, y: 10 },
            type: 'wall-outer',
            z,
            feedrate: 2400,
            extrusionWidth: 0.44,
            extrusionHeight: 0.2,
            extrusionAmount: 0.2,
        }],
        filamentUsed: 0.2 * (index + 1),
    }
}

describe('gcodeExport custom layer change gcode', () => {
    it('inserts custom layer change gcode at every layer', () => {
        const layers = [createTestLayer(0, 0.3), createTestLayer(1, 0.5)]
        const config = createTestConfig({
            customLayerChangeGcode: 'TIMELAPSE_TAKE_FRAME',
        })
        const gcode = exportGcode(layers, config)

        const matches = gcode.match(/TIMELAPSE_TAKE_FRAME/g)
        expect(matches).not.toBeNull()
        expect(matches!.length).toBe(2)
    })

    it('substitutes layer_num and layer_z variables', () => {
        const layers = [createTestLayer(0, 0.3), createTestLayer(1, 0.5)]
        const config = createTestConfig({
            customLayerChangeGcode: 'M117 Layer {layer_num} at Z={layer_z}',
        })
        const gcode = exportGcode(layers, config)

        expect(gcode).toContain('M117 Layer 0 at Z=0.300')
        expect(gcode).toContain('M117 Layer 1 at Z=0.500')
    })

    it('substitutes total_layer_count in layer change gcode', () => {
        const layers = [createTestLayer(0, 0.3), createTestLayer(1, 0.5), createTestLayer(2, 0.7)]
        const config = createTestConfig({
            customLayerChangeGcode: 'M73 P{layer_num} ; {layer_num}/{total_layer_count}',
        })
        const gcode = exportGcode(layers, config)

        expect(gcode).toContain('; 0/3')
        expect(gcode).toContain('; 2/3')
    })

    it('does not insert layer change gcode when not set', () => {
        const layers = [createTestLayer(0, 0.3)]
        const config = createTestConfig()
        const gcode = exportGcode(layers, config)

        // Should still have normal layer change markers
        expect(gcode).toContain(';LAYER_CHANGE')
        expect(gcode).toContain(';LAYER:0')
    })

    it('also substitutes config variables like nozzle_temp in layer change', () => {
        const layers = [createTestLayer(0, 0.3)]
        const config = createTestConfig({
            customLayerChangeGcode: 'SET_HEATER_TEMPERATURE HEATER=extruder TARGET={nozzle_temp}',
            nozzleTemp: 230,
        })
        const gcode = exportGcode(layers, config)

        expect(gcode).toContain('SET_HEATER_TEMPERATURE HEATER=extruder TARGET=230')
    })
})
