/**
 * G-code Export
 *
 * Converts ordered toolpath segments into G-code text.
 * Generates standard Marlin/Klipper-compatible G-code.
 */

import { LayerToolpath, SlicerConfig } from '../types'

/**
 * Format a G-code coordinate value
 */
function fmt(val: number, decimals = 3): string {
    return val.toFixed(decimals)
}

const PRIME_MAX_CROSS_SECTION_MM2 = 0.55
const MIN_GCODE_SEGMENT_LENGTH = 0.01

/**
 * Generate the G-code start sequence
 */
function generateStartGcode(config: SlicerConfig): string {
    const primeStartX = 5
    const primeEndX = 60
    const primeY = 5
    const primeDistance = Math.abs(primeEndX - primeStartX)
    const filamentArea = Math.PI * (config.filamentDiameter / 2) ** 2
    const primeCrossSection = Math.min(config.lineWidth * config.firstLayerHeight, PRIME_MAX_CROSS_SECTION_MM2)
    const primeExtrusion = (primeCrossSection * primeDistance) / filamentArea

    const lines: string[] = [
        '; Generated by Mainsail Slicer',
        `; Layer height: ${config.layerHeight}mm`,
        `; First layer height: ${config.firstLayerHeight}mm`,
        `; Nozzle diameter: ${config.nozzleDiameter}mm`,
        `; Filament diameter: ${config.filamentDiameter}mm`,
        `; Wall count: ${config.wallCount}`,
        `; Infill density: ${(config.infillDensity * 100).toFixed(0)}%`,
        `; Infill pattern: ${config.infillPattern}`,
        `; Print speed: ${config.printSpeed}mm/s`,
        `; Travel speed: ${config.travelSpeed}mm/s`,
        '',
        ';TYPE:Custom',
        'G90 ; Absolute positioning',
        'M82 ; Absolute extrusion',
        'G28 ; Home all axes',
        `M104 S${config.firstLayerNozzleTemp} ; Set nozzle temp`,
        `M140 S${config.firstLayerBedTemp} ; Set bed temp`,
        `M109 S${config.firstLayerNozzleTemp} ; Wait for nozzle temp`,
        `M190 S${config.firstLayerBedTemp} ; Wait for bed temp`,
        '',
        '; Prime line',
        'G1 Z2 F3000',
        `G1 X${fmt(primeStartX)} Y${fmt(primeY)} F${config.travelSpeed * 60}`,
        `G1 Z${fmt(config.firstLayerHeight)} F3000`,
        'G92 E0 ; Reset extruder before priming',
        `G1 X${fmt(primeEndX)} Y${fmt(primeY)} E${fmt(primeExtrusion, 5)} F${config.firstLayerSpeed * 60} ; Prime`,
        'G1 E-0.5 F1800 ; Retract slightly',
        'G92 E0 ; Reset extruder',
        '',
    ]
    return lines.join('\n')
}

/**
 * Generate the G-code end sequence
 */
function generateEndGcode(): string {
    const lines: string[] = [
        '',
        ';TYPE:Custom',
        'G91 ; Relative positioning',
        'G1 E-2 F1800 ; Retract',
        'G1 Z10 F3000 ; Lift',
        'G90 ; Absolute positioning',
        'G1 X5 Y200 F6000 ; Present print',
        'M104 S0 ; Turn off nozzle',
        'M140 S0 ; Turn off bed',
        'M84 ; Disable motors',
        'M107 ; Fan off',
    ]
    return lines.join('\n')
}

/**
 * Map move type to ;TYPE: comment (for toolpath visualization)
 */
function typeComment(type: string): string {
    switch (type) {
        case 'wall-outer': return ';TYPE:Outer wall'
        case 'wall-inner': return ';TYPE:Inner wall'
        case 'floor': return ';TYPE:Bottom solid infill'
        case 'roof': return ';TYPE:Top solid infill'
        case 'infill': return ';TYPE:Sparse infill'
        case 'support': return ';TYPE:Support'
        case 'skirt': return ';TYPE:Skirt'
        case 'brim': return ';TYPE:Brim'
        case 'travel': return ''
        default: return ''
    }
}

/**
 * Export a sliced model to G-code string.
 */
export function exportGcode(layers: LayerToolpath[], config: SlicerConfig): string {
    const lines: string[] = []
    lines.push(generateStartGcode(config))

    let currentE = 0
    let currentZ = 0
    let currentType = ''
    let lastFeedrate = 0
    let isRetracted = false
    // Track nozzle XY so we can insert missing travel moves.
    // Prime line ends at (60, 5).
    let curX = 60
    let curY = 5
    const travelFeedrate = config.travelSpeed * 60
    const minTravelForRetract = 1.5

    for (const layer of layers) {
        // Layer change
        lines.push(``)
        lines.push(`;LAYER_CHANGE`)
        lines.push(`;Z:${fmt(layer.z)}`)
        lines.push(`;LAYER:${layer.layerIndex}`)

        // Z-gap warning: detect jumps larger than 2× layer height
        const zJump = layer.z - currentZ
        if (currentZ > 0 && zJump > config.layerHeight * 2) {
            lines.push(`; WARNING: Z gap of ${fmt(zJump)}mm detected (expected ~${fmt(config.layerHeight)}mm)`)
        }

        lines.push(`G1 Z${fmt(layer.z)} F3000`)
        currentZ = layer.z

        // Periodic E reset every 50 layers to prevent floating-point drift
        if (layer.layerIndex > 0 && layer.layerIndex % 50 === 0) {
            lines.push(`G92 E0 ; reset E counter`)
            currentE = 0
        }

        // Set per-layer temperatures and fan
        if (layer.layerIndex === 1) {
            // Switch to normal temps after first layer
            lines.push(`M104 S${config.nozzleTemp}`)
            lines.push(`M140 S${config.bedTemp}`)
        }
        if (layer.layerIndex === config.fanStartLayer) {
            lines.push(`M106 S${config.fanSpeed}`)
        }

        for (const seg of layer.segments) {
            const dx = seg.to.x - seg.from.x
            const dy = seg.to.y - seg.from.y
            const segLen = Math.sqrt(dx * dx + dy * dy)
            if (segLen < MIN_GCODE_SEGMENT_LENGTH && Math.abs(seg.extrusionAmount) < 1e-5) {
                continue
            }

            // Type comments
            const tc = typeComment(seg.type)
            if (tc && tc !== currentType) {
                lines.push(tc)
                currentType = tc
            }

            if (seg.type === 'travel') {
                // Handle retraction before travel
                if (seg.extrusionAmount < 0 && !isRetracted) {
                    currentE += seg.extrusionAmount
                    lines.push(`G1 E${fmt(currentE, 5)} F${config.retractSpeed * 60}`)
                    isRetracted = true
                    // Z-hop
                    if (config.retractLift > 0) {
                        lines.push(`G1 Z${fmt(currentZ + config.retractLift)} F3000`)
                    }
                }
                // Travel move
                const f = seg.feedrate !== lastFeedrate ? ` F${Math.round(seg.feedrate)}` : ''
                lines.push(`G0 X${fmt(seg.to.x)} Y${fmt(seg.to.y)}${f}`)
                lastFeedrate = seg.feedrate
                curX = seg.to.x
                curY = seg.to.y
            } else {
                // Safety: if nozzle isn't at seg.from, insert a travel first.
                const gapX = seg.from.x - curX
                const gapY = seg.from.y - curY
                const gap = Math.sqrt(gapX * gapX + gapY * gapY)
                if (gap > 0.01) {
                    // Retract for long gaps
                    if (gap > minTravelForRetract && !isRetracted) {
                        currentE -= config.retractDistance
                        lines.push(`G1 E${fmt(currentE, 5)} F${config.retractSpeed * 60}`)
                        isRetracted = true
                        if (config.retractLift > 0) {
                            lines.push(`G1 Z${fmt(currentZ + config.retractLift)} F3000`)
                        }
                    }
                    lines.push(`G0 X${fmt(seg.from.x)} Y${fmt(seg.from.y)} F${travelFeedrate}`)
                    lastFeedrate = travelFeedrate
                    curX = seg.from.x
                    curY = seg.from.y
                }

                // Un-retract if needed
                if (isRetracted) {
                    // Drop z-hop
                    if (config.retractLift > 0) {
                        lines.push(`G1 Z${fmt(currentZ)} F3000`)
                    }
                    currentE += config.retractDistance
                    lines.push(`G1 E${fmt(currentE, 5)} F${config.retractSpeed * 60}`)
                    isRetracted = false
                }

                // Extrusion move
                currentE += seg.extrusionAmount
                const f = seg.feedrate !== lastFeedrate ? ` F${Math.round(seg.feedrate)}` : ''
                lines.push(`G1 X${fmt(seg.to.x)} Y${fmt(seg.to.y)} E${fmt(currentE, 5)}${f}`)
                lastFeedrate = seg.feedrate
                curX = seg.to.x
                curY = seg.to.y
            }
        }
    }

    lines.push(generateEndGcode())

    return lines.join('\n')
}

/**
 * Compute summary statistics from the sliced result
 */
export function computeStats(layers: LayerToolpath[], config: SlicerConfig): {
    layerCount: number
    filamentUsedMm: number
    filamentUsedM: number
    filamentWeightG: number
    estimatedTimeS: number
    estimatedTimeFormatted: string
} {
    const layerCount = layers.length
    const filamentUsedMm = layers.length > 0 ? layers[layers.length - 1].filamentUsed : 0
    const filamentUsedM = filamentUsedMm / 1000

    // PLA density ~1.24 g/cm³
    const filamentRadius = config.filamentDiameter / 2
    const filamentVolumeMm3 = Math.PI * filamentRadius * filamentRadius * filamentUsedMm
    const filamentWeightG = (filamentVolumeMm3 / 1000) * 1.24 // mm³ → cm³ → g

    // Estimate print time from all segments
    let totalTimeS = 0
    for (const layer of layers) {
        for (const seg of layer.segments) {
            const dx = seg.to.x - seg.from.x
            const dy = seg.to.y - seg.from.y
            const dist = Math.sqrt(dx * dx + dy * dy)
            if (seg.feedrate > 0) {
                totalTimeS += (dist / seg.feedrate) * 60 // feedrate in mm/min
            }
        }
    }

    // Add time for layer changes, retractions, etc. (~10% overhead)
    totalTimeS *= 1.1

    const hours = Math.floor(totalTimeS / 3600)
    const mins = Math.round((totalTimeS % 3600) / 60)
    const estimatedTimeFormatted = hours > 0 ? `${hours}h ${mins}m` : `${mins}m`

    return {
        layerCount,
        filamentUsedMm: Math.round(filamentUsedMm * 100) / 100,
        filamentUsedM: Math.round(filamentUsedM * 100) / 100,
        filamentWeightG: Math.round(filamentWeightG * 10) / 10,
        estimatedTimeS: Math.round(totalTimeS),
        estimatedTimeFormatted,
    }
}
